2025-01-16 15:56:55,312 | WARNING | Неверный тип данных для объекта Runner
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject9\test_12_4.py", line 20, in test_run
    runner_run = rt_with_exceptions.Runner(' Run2', -5)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject9\rt_with_exceptions.py", line 11, in __init__
    raise ValueError(f'Скорость не может быть отрицательной, сейчас {speed}')
ValueError: Скорость не может быть отрицательной, сейчас -5
2025-01-16 15:56:55,321 | WARNING | Неверная скорость для Runner
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject9\test_12_4.py", line 10, in test_walk
    runner_walk = rt_with_exceptions.Runner(10, 20)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\PycharmProjects\pythonProject9\rt_with_exceptions.py", line 6, in __init__
    raise TypeError(f'Имя может быть только строкой, передано {type(name).__name__}')
TypeError: Имя может быть только строкой, передано int
